### PR TITLE
Dependencies and documentation

### PR DESCRIPTION
**Pull request by Hendrik1704**
This updates the dependencies:
We need now python 3.8 to build the package. This is required by the fastjet version update.
Matplotlib dependency is removed and for numpy and scipy we require minimum versions instead of fixed ones.

The CONTRIBUTORS file is now updated (similar to the SMASH one). The Author names are now in alphabetical order. 

I fixed several documentation issues with missing functions and a missing `_static` folder resulting in a warning during the build of the documentation.
One issue when building the documentation with sphinx is still there in the Particle class docstring:
`docstring of Particle.Particle:44: ERROR: Unexpected indentation`
This is something I tried to fix for several hours now without any progress. The string looks perfectly fine and there is no wrong indentation visible.

Maybe this can also influence the behavior mentioned in issue #154.

### CODE REVIEW

**Comment by NGoetz** [comment]
Fastjet has additional non-python dependencies: https://github.com/scikit-hep/fastjet
With these installed, I can install sparkx
The question is if we want to add this list of prerequisities, as this is quite massive. Alternatively, one could also try to have optional fastjet support as it, afaik, only affects certain functionalities. Additionally, the wheel building for fastjet is extremely slow on installation.
Additionally, pip knows no version of `imp`, which fastjet requires. Therefore I cannot manage to install fastjet. I will try on though.
What is your opinion @nilssass ?

**Comment by Hendrik1704** [comment]
She just used `pip install sparkx` and then it downloads+installs everything automatically.

**Comment by NGoetz** [comment]
Okay, can she test also to clone and use the editable install? Maybe this caused the issue after all.
Honestly, I am very confused by now.

**Comment by Hendrik1704** [comment]
We have just tested it in a `venv` on her machine and it is working there as well.

**Review by NGoetz — APPROVED** [review]
After testing it on a fresh ubuntu machine, I think we can be sure now that the fastjet dependency should in general work. I would for now merge this and close the issue, but in general be aware that this can be an issue during installs.
For future reference: If the jet analysis is not needed, the requirement can be always removed during install.

**Pull request merged**
